name: Minify Workflow
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository
      - uses: actions/checkout@v3
        with:
          ref: "main"

      - name: Auto Minify
        uses: nizarmah/auto-minify@v2.1
        with:
          directory: '.'
          output: '.'
          js_engine: 'uglify-js'
          maxdepth: 1

      # Auto-commit to repository
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: ''
          commit_message: Minify source code
          branch: minified
          push_options: '--force'
          skip_checkout: true
